---
- name: Add Loopback CoreTAAS
  hosts: ctaas
  gather_facts: no
  become: yes
  tasks: 
    - name: Add Loopback
      ios_command:
        commands:
          - conf t
          - int lo 100
          - ip add 100.100.92.2 255.255.255.255
          - end

- name: Add Loopback CoreBABA
  hosts: cbaba
  gather_facts: no
  become: yes
  tasks: 
    - name: Add Loopback
      ios_command:
        commands:
          - conf t
          - int lo 100
          - ip add 100.100.92.4 255.255.255.255
          - end
- name: Add Loopback CUCM
  hosts: cucm
  gather_facts: no
  become: yes
  tasks: 
    - name: Add Loopback
      ios_command:
        commands:
          - conf t
          - int lo 100
          - ip add 100.100.92.8 255.255.255.255
          - end

- name: Add Loopback EDGE
  hosts: edge
  gather_facts: no
  become: yes
  tasks: 
    - name: Add Loopback
      ios_command:
        commands:
          - conf t
          - int lo 100
          - ip add 100.100.92.92 255.255.255.255
          - end
